
export const sample_foods: any[] = [
  {
    id:'1',
    name: 'Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/pizza.jpg',
    tags: ['SlowFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Avo Taost',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle-east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/avotoast.jpg',
    tags: ['FastFood', 'Breakfast'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/burger.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/fries.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Pasta Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/pastasoap.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Pancakes',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/pancakes.jpg',
    tags: ['FastFood', 'Pancakes', 'BreakFast'],
  },
  {
    id:'7',
    name: 'Donuts',
    price: 3,
    cookTime: '5-10',
    favorite: false,
    origins: ['America'],
    stars: 4.0,
    imageUrl: 'assets/donuts.jpg',
    tags: ['FastFood', 'Donuts', 'Snack'],
  },
  {
    id:'8',
    name: 'Fruit Bowl',
    price: 3,
    cookTime: '0-5',
    favorite: true,
    origins: ['Africa'],
    stars: 4.0,
    imageUrl: 'assets/fruitbowl.jpg',
    tags: ['Healthy', 'Fruit', 'Snack'],
  },
]

export const sample_tags:any[]=[
  {name:'All',count:8},
  {name:'FastFood',count:6},
  {name:'Pizza',count:1},
  {name:'Lunch',count:4},
  {name:'SlowFood',count:5},
  {name:'Healthy',count:1},
  {name:'Fry',count:2},
  {name:'Soup',count:1},
]
